version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
        - zookeeper
    environment:
      KAFAKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.0.1
    container_name: control-center
    depends_on:
      - zookeeper
      - broker
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: broker:29092
      CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_CONNECT_CLUSTER: "connect:8083"
      CONTROL_CENTER_KSQL_URL: "http://ksql-server:8088"
      CONTROL_CENTER_KSQL_ADVERTISED_URL: "http://localhost:8088"
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONTROL_CENTER_SCHEMA_REGISTRY_ADVERTISED_URL: "http://localhost:8081"
      CONTROL_CENTER_CONNECT_CONTROL_CENTER_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_CONNECT_CONTROL_CENTER_TOPIC_REPLICATION_FACTOR: 1
      CONTROL_CENTER_KSQL_CONTROL_CENTER_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_KSQL_CONTROL_CENTER_TOPIC_REPLICATION_FACTOR: 1
      CONTROL_CENTER_KSQL_METASTORE_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_KSQL_METASTORE_TOPIC_REPLICATION_FACTOR: 1
      CONTROL_CENTER_KSQL_SERVICE_ID: "ksql_"
      CONTROL_CENTER_KSQL_STREAMS_NUM_STREAM_THREADS: 1
      CONTROL_CENTER_KSQL_STREAMS_NUM_REPLICATION: 1
      CONTROL_CENTER_KSQL_STREAMS_STATE_DIR: "/tmp/ksql-server"
      CONTROL_CENTER_KSQL_STREAMS_NUM_STANDBY_REPLICAS: 1
      CONTROL_CENTER_KSQL_STREAMS_NUM_PARTITIONS: 1
      CONTROL_CENTER_KSQL_STREAMS_REPLICATION_FACTOR: 1
      CONTROL_CENTER_KSQL_STREAMS_COMMIT_INTERVAL_MS: 2000
      CONTROL_CENTER_KSQL_STREAMS_CACHE_MAX_BYTES_BUFFERING: 0
      PORT: 9021
